server.port=8081
spring.application.name=NauJava
app.name=LibraryApp
app.version=1.0.0
management.endpoints.web.exposure.include=*
spring.datasource.url=jdbc:postgresql://localhost:5432/library_db
spring.datasource.username=postgres
spring.datasource.password=01072005
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true